services:
  postgres:
    image: postgres
    container_name: gochat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"