// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (room_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, room_id, user_id, content, created_at
`

type InsertMessageParams struct {
	RoomID  int64  `json:"room_id"`
	UserID  int64  `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.RoomID, arg.UserID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT m.id, m.room_id, m.user_id, m.content, m.created_at, u.nickname
FROM messages m
JOIN users u ON u.id = m.user_id
WHERE m.room_id = $1
ORDER BY m.created_at DESC
LIMIT $2
`

type ListRecentMessagesParams struct {
	RoomID int64 `json:"room_id"`
	Limit  int32 `json:"limit"`
}

type ListRecentMessagesRow struct {
	ID        int64              `json:"id"`
	RoomID    int64              `json:"room_id"`
	UserID    int64              `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Nickname  string             `json:"nickname"`
}

func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]ListRecentMessagesRow, error) {
	rows, err := q.db.Query(ctx, listRecentMessages, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentMessagesRow
	for rows.Next() {
		var i ListRecentMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.Nickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
