// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        int64              `json:"id"`
	RoomID    int64              `json:"room_id"`
	UserID    int64              `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Nickname  string             `json:"nickname"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
