// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateRoom(ctx context.Context, name string) (Room, error)
	CreateUser(ctx context.Context, nickname string) (User, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	ListRooms(ctx context.Context) ([]Room, error)
}

var _ Querier = (*Queries)(nil)
