// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (nickname)
VALUES ($1)
RETURNING id, nickname, created_at
`

func (q *Queries) CreateUser(ctx context.Context, nickname string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, nickname)
	var i User
	err := row.Scan(&i.ID, &i.Nickname, &i.CreatedAt)
	return i, err
}
